# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.java.home=/usr/lib/jvm/java-21-openjdk-amd64
# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.5
loader_version=0.19.2
# Mod Properties
mod_version=2.0.3
maven_group=mc.ardacraft
archives_base_name=aclodgrabber
# Dependencies
# check this on https://fabricmc.net/develop
fabric_version=0.141.3+1.21.11